version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: sales
      POSTGRES_DB: CarDealership_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma-db
    restart: always
    environment:
      CHROMA_PORT: 8000
      CHROMA_DB_DIR: /data/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data/chroma
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_SQLITE_DATA_MODE=filesystem
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_SECURE_COOKIE=false
      - TZ=UTC
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
volumes:
  postgres_data:
  chroma_data:
  n8n_data:
